version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
  test:
    build: .
    volumes:
      - "./:/app"
    depends_on:
      - db
    tty: true
    stdin_open: true
