version: '3'
services:
  app:
    build: .
    command: bundle exec unicorn -p 3000 -c /fabnavi/config/unicorn.rb
    volumes:
      - .:/fabnavi
      - public-data:/fabnavi/public
      - tmp-data:/fabnavi/tmp
      - log-data:/fabnavi/log
    depends_on:
      - db
  db:
    image: mysql:5.6
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: nginx
    volumes:
      - public-data:/fabnavi/public
      - tmp-data:/fabnavi/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: